### ISSUE TITLE
Example output is different

### ISSUE THREAD

**Issue by LihuaJulieZhu** [MyungjaeSong/Paired-Library#2]
Myungjae,

I ran the input example but got the following results, which are different from the provided output_example.txt. Could you please let me the reasons and how to fix the issue?Thanks!

Best regards,

Julie

Target number   34 bp target sequence (4 bp + PAM + 23 bp protospacer + 3 bp)           "Chromatin accessibility (1= DNase I hypersensitive sites, 0 = Dnase I non-sensitive sites)"    Seq-deepCpf1 Score      DeepCpf1 Score
1       TGACTTTGAATGGAGTCGTGAGCGCAAGAACGCT              1       55.437206       45.836536
2       GTTATTTGAGCAATGCCACTTAATAAACATGTAA              0       78.500427       11.127628

**Comment by PeterDeWeirdt** [comment]
Julie,

I had a similar issue. One of the paper's authors informed me that when you install keras by default it uses tensorflow as the backend. Instead, you want to [change to the theano backend](https://keras.io/backend/) for deepCpf1. This would be good to document in a README for deepCpf1. 

Peter

**Comment by LihuaJulieZhu** [comment]
Thanks, Peter!

Best regards,

Julie

On Sep 27, 2018, at 10:54 AM, Peter DeWeirdt <notifications@github.com<mailto:notifications@github.com>> wrote:


Julie,

I had a similar issue. One of the paper's authors informed me that when you install keras by default it uses tensorflow as the backend. Instead, you want to change to the theano backend<https://urldefense.proofpoint.com/v2/url?u=https-3A__keras.io_backend_&d=DwMFaQ&c=WJBj9sUF1mbpVIAf3biu3CPHX4MeRjY_w4DerPlOmhQ&r=3IbW-yoIQpGZOKgd4i2bgmPHhwHHF5gJMlij5cC5bLU&m=VNqxCKyaEWpoaGkIgWVewQxL4-1abVmNPOGzxx93FXU&s=j0NLcQvWMoXVZmL17_Wd6yp6oVi_DvR4evpL_HZtHH4&e=> for deepCpf1. This would be good to document in a README for deepCpf1.

Peter
