### ISSUE TITLE
Predicting LbCpf1 Activity

### ISSUE THREAD

**Issue by hello1910** [MyungjaeSong/Paired-Library#7]
Hi Dr.Song,

I'm so sorry to bother you again! You've been so incredibly helpful that I thought I'd ask one last question. I really appreciate your time.

I'm trying to train a model to predict guide activity for LbCpf1, but I'm unable to find numerical data in the online database link that you sent me. Sorry, am I missing something? 

Thank you so so much!!

**Comment by hello1910** [comment]
Hi Dr.Song,

Sorry to bother you again---I was wondering if you had a chance to read my previous question?
Of course, if you don't have time, I completely understand.

Thank you so much for your help so far!

**Comment by MyungjaeSong** [comment]
Dear Sarah Roden

I am sorry to reply late. I had a vacation and too busy.

Previously, I sent the information that is raw sequencing data. So you must
analyze raw data.

Sincerely.

Myungjae Song


2019년 8월 14일 (수) 오전 10:16, Sarah Roden <notifications@github.com>님이 작성:

**Comment by hello1910** [comment]
Thank you so much Dr.Song! I really appreciate your patience.
Does the raw sequencing data contain only the PAM determination data for LbCpf1, or does it also contain the activity profile data for LbCpf1?

It appears to only contain the PAM determination data, but I'm not sure.

**Comment by MyungjaeSong** [comment]
Dear Sarah Roden

Raw data contain only PAM determination data. And we don't have the
activity profile data for LbCpf1.

Thank you

Myungjae Song

2019년 8월 24일 (토) 오전 12:30, Sarah Roden <notifications@github.com>님이 작성:

**Comment by hello1910** [comment]
Hi Dr.Song,

Thank you so much for your response. 

Sorry, when I read the paper, it seemed like activity profile data was also collected for LbCpf1. Would it be possible to access this data, or am I misunderstanding?

I sincerely appreciate your patience and I apologize for troubling you.
Thank you.

**Comment by MyungjaeSong** [comment]
Dear Sarah Roden

I think that you are misunderstanding.

In our paper, 3 figures are about LbCpf1.

Figure 2 and Supplementary Figure 7 : PAM determination
supplementary Figure 9 : Comparison of indel frequencies induced by AsCpf1,
LbCpf1, and SpCas9 at endogenous sites (This data is not our data)

I am so sorry that I can't give help.

If you have any concerns, please let me know.

Sincerely.

Myungjae Song


2019년 8월 29일 (목) 오전 3:27, Sarah Roden <notifications@github.com>님이 작성:

**Comment by hello1910** [comment]
Hi Dr.Song,

Thank you so much for your informative reply. 

Last question, sorry! Do you potentially know of other papers that have collected activity profile data on LbCpf1? I searched but could not find any.

Thank you so much for your help!

**Comment by MyungjaeSong** [comment]
Dear Sarah Roden

I am sorry that I don't know other papers.

Sincerely.

Myungjae Song

2019년 8월 31일 (토) 오전 11:19, Sarah Roden <notifications@github.com>님이 작성:

**Comment by hello1910** [comment]
Thank you so much!
